package procatering;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;

import database.DBConnection;
import database.SecurityChecker;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

@SuppressWarnings("serial")
public class Gui extends javax.swing.JFrame {
    private DBConnection db;
	private boolean admin;
	private JPanel subscriptionPanel;
    /**
     * Creates new form Gui
     */
    public Gui() {
    	admin = false;
        initComponents();
        db = new DBConnection(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuFindButton = new javax.swing.JButton();
        menuRegButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menuSingleOrderButton = new javax.swing.JButton();
        menuSubscriptionButton = new javax.swing.JButton();
        menuExistingButton = new javax.swing.JButton();
        backendMenu = new javax.swing.JPanel();
        backend1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        backend2 = new javax.swing.JButton();
        backend3 = new javax.swing.JButton();
        backend4 = new javax.swing.JButton();
        backend5 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        employee_ID_input = new javax.swing.JTextField();
        Employee_ID_input_label = new javax.swing.JLabel();
        Password_input_label = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        loginErrorMessage_label = new javax.swing.JLabel();
        loginErrorMessage_label.setVisible(false);
        loginErrorMessage_label.setForeground(Color.RED);
        customersPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        customerSearchButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        customerPostalCodeInput = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        customerEditButton = new javax.swing.JButton();
        customerPhoneInput = new javax.swing.JTextField();
        customerRegisterButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerNotesInput = new javax.swing.JTextArea();
        customerLnameInput = new javax.swing.JTextField();
        customerCorporateNameInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        customerAddressInput = new javax.swing.JTextField();
        customerFnameInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        customerEmailInput = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        customerBirthInput = new javax.swing.JTextField();
        singleOrderPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        singleOrderMonthList = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        singleOrderDateList = new javax.swing.JList();
        jLabel20 = new javax.swing.JLabel();
        singleOrderDate = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel23 = new javax.swing.JLabel();
        subscriptionPanel = new JPanel();
        existPanel = new JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customers:");

        menuFindButton.setLabel("Find");
        menuFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFindButtonActionPerformed(evt);
            }
        });

        menuRegButton.setLabel("Register new");

        jLabel2.setText("Orders:");

        menuSingleOrderButton.setText("Single order");
        menuSingleOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSingleOrderButtonActionPerformed(evt);
            }
        });

        menuSubscriptionButton.setText("Subscription");
        
        menuSubscriptionButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
                menuSubscriptionButtonActionPerformed(evt);
        	}
        });
        
        menuExistingButton.setText("Existing");
        menuExistingButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		menuExistButtonActionPerformed(evt);
        	}
        });
        
        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuSingleOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuExistingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuSubscriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuFindButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuRegButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSingleOrderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSubscriptionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuExistingButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFindButton.getAccessibleContext().setAccessibleName("findButton");

        backend1.setText("Employees");
        backend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backend1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Backend:");

        backend2.setText("Customers");

        backend3.setText("Orders");

        backend4.setText("Dishes");

        backend5.setText("Economics");

        javax.swing.GroupLayout backendMenuLayout = new javax.swing.GroupLayout(backendMenu);
        backendMenu.setLayout(backendMenuLayout);
        backendMenuLayout.setHorizontalGroup(
            backendMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backendMenuLayout.createSequentialGroup()
                .addGroup(backendMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backendMenuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(backend1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backend2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backend3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backend4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backend5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backendMenuLayout.setVerticalGroup(
            backendMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backendMenuLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backend1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backend2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backend3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backend4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backend5)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        loginButton.setText("login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        employee_ID_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_ID_inputActionPerformed(evt);
            }
        });

        Employee_ID_input_label.setText("Employee id:");

        Password_input_label.setText("Password:");

        loginErrorMessage_label.setText("This field requires a numeric value. Type a number");
        loginErrorMessage_label.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                loginErrorMessage_labelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Employee_ID_input_label)
                            .addComponent(Password_input_label))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employee_ID_input, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(password_input)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginButton)))
                .addGap(18, 18, 18)
                .addComponent(loginErrorMessage_label)
                .addContainerGap(463, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee_ID_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Employee_ID_input_label)
                    .addComponent(loginErrorMessage_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_input_label)
                    .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jLabel7.setText("Address:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        customerSearchButton.setText("Search");
        customerSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerSearchButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Last name:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel11.setText("Customers:");

        jLabel8.setText("Postal code:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        customerEditButton.setText("Edit");

        customerRegisterButton.setText("Register");
        customerRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRegisterButtonActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        customerNotesInput.setColumns(20);
        customerNotesInput.setRows(5);
        jScrollPane1.setViewportView(customerNotesInput);

        jLabel9.setText("Phone number:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        customerFnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFnameInputActionPerformed(evt);
            }
        });

        jLabel6.setText("Corporate name:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setText("First name:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel10.setText("Notes:");

        customerEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerEmailInputActionPerformed(evt);
            }
        });

        jLabel21.setText("email");

        jLabel24.setText("Date of birth:");

        javax.swing.GroupLayout customersPanelLayout = new javax.swing.GroupLayout(customersPanel);
        customersPanel.setLayout(customersPanelLayout);
        customersPanelLayout.setHorizontalGroup(
            customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPanelLayout.createSequentialGroup()
                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(60, 60, 60)
                                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(customersPanelLayout.createSequentialGroup()
                                        .addComponent(customerSearchButton)
                                        .addGap(28, 28, 28)
                                        .addComponent(customerRegisterButton))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerBirthInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(customerEmailInput)
                            .addComponent(customerAddressInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(customerCorporateNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(customerLnameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(customerFnameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(customerPhoneInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(customerPostalCodeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addGap(38, 38, 38)))
                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customerEditButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        customersPanelLayout.setVerticalGroup(
            customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(customerEditButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(customersPanelLayout.createSequentialGroup()
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(customerFnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerLnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerCorporateNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerPostalCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerPhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(customerBirthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerRegisterButton)
                            .addComponent(customerSearchButton))))
                .addContainerGap())
        );

        singleOrderPanel.setPreferredSize(new java.awt.Dimension(700, 351));

        jLabel18.setText("Single order:");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel12.setText("Order information:");

        jLabel13.setText("Customer:");

        jLabel14.setText("customer name");

        jLabel15.setText("Notes:");

        jLabel16.setText("Month:");

        singleOrderMonthList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "January", "February", "March", "April", "May",
                "June", "July", "August", "September", "October", "November", "December" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(singleOrderMonthList);

        jLabel17.setText("Year:");

        singleOrderYearList.setModel(new javax.swing.AbstractListModel() {
            int[] strings = { 2013, 2014, 2015 };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(singleOrderYearList);

        jLabel19.setText("Day:");

        singleOrderDateList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = new String[31];
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return i+1; }
        });
        singleOrderDateList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                singleOrderDateListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(singleOrderDateList);

        jLabel20.setText("Date:");

        singleOrderDate.setText("datevalue");

        jLabel22.setText("Time:");

        String[] clock = new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00","13:00", "14:00", "15:00","16:00", "17:00", "18:00","19:00", "20:00", "21:00"};
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(clock));

        jCheckBox1.setText("+30min");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Add order");

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "04/feb - 12:00", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList2);

        jLabel23.setText("=>");

        javax.swing.GroupLayout singleOrderPanelLayout = new javax.swing.GroupLayout(singleOrderPanel);
        singleOrderPanel.setLayout(singleOrderPanelLayout);
        singleOrderPanelLayout.setHorizontalGroup(
            singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(singleOrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singleOrderPanelLayout.createSequentialGroup()
                        .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(singleOrderPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(singleOrderPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(singleOrderDate))
                                    .addGroup(singleOrderPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox1))
                                    .addGroup(singleOrderPanelLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(singleOrderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel14))
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane6))
                        .addGap(26, 26, 26))))
        );
        singleOrderPanelLayout.setVerticalGroup(
            singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(singleOrderPanelLayout.createSequentialGroup()
                        .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(singleOrderDate)
                            .addComponent(jLabel20))
                        .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(singleOrderPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBox1)
                                        .addComponent(jLabel15))))
                            .addGroup(singleOrderPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(singleOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jLabel23))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        customersPanel.setVisible(false);
        singleOrderPanel.setVisible(false);
        existPanel.setVisible(false);
        subscriptionPanel.setVisible(false);
        JLabel lblExisting = new JLabel("Existing");
        existPanel.add(lblExisting);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanelLayout.setHorizontalGroup(
        	mainPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(mainPanelLayout.createSequentialGroup()
        			.addGroup(mainPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(mainPanelLayout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(mainPanelLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(customersPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(singleOrderPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(loginPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(mainPanelLayout.createSequentialGroup()
        					.addGap(50)
        					.addComponent(subscriptionPanel, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE)
        					.addGap(60)
        					.addComponent(existPanel, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(545, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
        	mainPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(mainPanelLayout.createSequentialGroup()
        			.addGroup(mainPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(mainPanelLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(customersPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(mainPanelLayout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(singleOrderPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(mainPanelLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(loginPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(28)
        			.addGroup(mainPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(subscriptionPanel, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
        				.addComponent(existPanel, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(37, Short.MAX_VALUE))
        );
        
        JLabel lblSubscription = new JLabel("Subscription");
        subscriptionPanel.add(lblSubscription);
        mainPanel.setLayout(mainPanelLayout);

        mainMenu.setVisible(false);
        backendMenu.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backendMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backendMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSubscriptionButtonActionPerformed(ActionEvent evt) {
		setView("subscription", admin);
	}
    
    private void menuExistButtonActionPerformed(ActionEvent evt) {
		setView("existing", admin);
	}

	private void backend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backend1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backend1ActionPerformed

    private void customerFnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFnameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerFnameInputActionPerformed
    
    //////////////////////////////////////////////////////////////////////////////////////////////////////
    //							MENU BUTTON CLICK HANDLING FOLLOWS										//
    //////////////////////////////////////////////////////////////////////////////////////////////////////
    private void menuFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFindButtonActionPerformed
        
    	setView("find", admin);
          DefaultListModel<String> nameList = new DefaultListModel<>();
            try(ResultSet rs = db.gQuery("select firstname, lastname from customer");){
                String fName;
                //String mName;
                String lName;
                while(rs.next()){
                    fName = rs.getString("firstname")+" ";
                    lName = rs.getString("lastname");
//                    if(rs.getString("middlename") == null){
//                        mName = "";
//                    }else{
//                        mName =rs.getString("middlename")+" ";
//                    }
                    nameList.addElement(fName  + lName);
                }
                
                jList1 = new javax.swing.JList(nameList);
                jScrollPane2.setViewportView(jList1);
               // try{db.disconnect();}catch(SQLException e){System.err.println("error"+e);}
            }catch(SQLException e){
                System.err.println("exception while trying to fetch customers:"+e);
            }
            
        
        
            // TODO skriv penis om skaft
    }//GEN-LAST:event_menuFindButtonActionPerformed

    private void customerSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerSearchButtonActionPerformed
        if(customerFnameInput.getText() != null && !customerFnameInput.getText().equals("")){
            //perform search
        } else{
            JOptionPane.showMessageDialog(null, "please insert a value in name or phone");
        }
    }//GEN-LAST:event_customerSearchButtonActionPerformed

    private void menuSingleOrderButtonActionPerformed(java.awt.event.ActionEvent evt){
    	setView("singleOrder", admin); //Sets view
    }

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    
    private void singleOrderDateListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_singleOrderDateListValueChanged
        if(!singleOrderYearList.getValueIsAdjusting() && !singleOrderMonthList.getValueIsAdjusting()){
            String input = singleOrderDateList.getSelectedValue().toString() + " / " + singleOrderMonthList.getSelectedValue().toString()+" - "+ singleOrderYearList.getSelectedValue().toString();
            singleOrderDate.setText(input);                // TODO add your handling code here:
        }
    }//GEN-LAST:event_singleOrderDateListValueChanged

    private void employee_ID_inputActionPerformed(java.awt.event.ActionEvent evt) {
    	// TODO add your handling code here:
    }
    
    
    
    
    //////////////////////////////////////////////////////////////////////////////////////////////////////
    //							HELP METHODS															//
    //////////////////////////////////////////////////////////////////////////////////////////////////////

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    	 boolean login = false;
         SecurityChecker checker = new SecurityChecker();
         int employee_id = -1;
                 try{
                 	employee_id = Integer.parseInt(employee_ID_input.getText().trim());
                 }catch(NumberFormatException num){
                 	employee_ID_input.setText("");
                 	errorTextHandler("The employee ID field must be a number");
                 }
         char[] password = password_input.getPassword();
         String password_s = "";
         for (int i = 0; i < password.length; i++) {
				password_s = password_s + password[i];
			}
         /* The login */
         admin  = checker.checkAdmin(); // logs in admin
         login = checker.checkPassword(employee_id, password_s); //Checks whether the password matches the one stored on the specific user
         if(login == true && employee_id != -1){
            loginErrorMessage_label.setVisible(false); //If there has been an error, the label is removed.
            mainMenu.setVisible(true);
            setView("find", admin); //See change view
         }else if(login == false && employee_id !=-1){
         	errorTextHandler("The password or employee ID wrong, please check input."); //Displays an errorMessage
         }
     
 }

    private void customerRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	Person temp;
        try{
            String fname    = customerFnameInput.getText();
            String lname    = customerLnameInput.getText();
            if(customerCorporateNameInput.getText() != null && !customerCorporateNameInput.getText().equals("")){
                String corpName = customerCorporateNameInput.getText();
            }
            String adr      = customerAddressInput.getText();
            String post     = customerPostalCodeInput.getText();
            String phone    = customerPhoneInput.getText();
            String dob      = customerBirthInput.getText();
            String e        = customerEmailInput.getText();
//          String notes    = customerNotesInput.getText();
//          temp = new Customer(adr, dob, fname,  lname, phone, e);
            db.eQuery("INSERT INTO customer VALUES(DEFAULT,'"+fname+"',DEFAULT,'"+lname+"','"+phone+"','"+adr+"','"+post+"')");
        }catch(Exception e){
            System.out.println("EXCEPTION: You have to fill in the required infomation.\n"+e);
        }
        
    }

    private void customerEmailInputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void loginErrorMessage_labelAncestorAdded(javax.swing.event.AncestorEvent evt) {
     // TODO add your handling code here:
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////////
    //											HELP METHODS											//
    //////////////////////////////////////////////////////////////////////////////////////////////////////
    private void errorTextHandler(String text){
    	loginErrorMessage_label.setText(text);
        loginErrorMessage_label.setVisible(true);
    }

    /** private method changeView takes a viewName as a parameter and changes the gui to the new view. 
     * @param view is a string describing witch of the view that should be selected.
     * @param admin is a boolean that chooses wether admin-tools is shown.
     * @author Jørgen Lien Sellæg
     * @return N/A
     * */
    private void setView(String view, boolean admin){
    	switch (view.toLowerCase().trim()) {
    		/* This view is the initial login.*/
			default:
				loginPanel.setVisible(false);
	            customersPanel.setVisible(false);
	            singleOrderPanel.setVisible(false);
	            subscriptionPanel.setVisible(false);
	            existPanel.setVisible(false);
			break;
			/* This view activates upon the hit of the  */
			case "find":
				setView("", admin);
	            customersPanel.setVisible(true);
			break;
		
			/* reg new?*/
			case "regnew":
				setView("", admin);
	            customersPanel.setVisible(true);
			break;
			/* Dok */
			case "singleorder":
				setView("", admin);
				singleOrderPanel.setVisible(true);
				break;
			/* Dok */
			case "subscription":
				setView("",admin);
				subscriptionPanel.setVisible(true);
				break;
			/* Dok */	//TODO Documentation and imp
			case "existing":
				setView("",admin);
				existPanel.setVisible(true);
				break;
			/* Dok */	//TODO Documentation and imp
			case "employees":
				setView("",admin);
				break;
			/* Dok */	//TODO Documentation and imp
			case "customers":
				setView("", admin);
				break;
			/* Dok */	//TODO Documentation and imp
			case "orders":
				setView("", admin);
				break;
			/* Dok */	//TODO Documentation and imp
			case "dishes":
				setView("", admin);
				break;
			/* Dok */ 	//TODO Documentation and imp
			case "economics":
				setView("", admin);
				break;
			case "logout":
				setView("login", admin);
				break;
		}
    	if(admin)
          	 backendMenu.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backend1;
    private javax.swing.JButton backend2;
    private javax.swing.JButton backend3;
    private javax.swing.JButton backend4;
    private javax.swing.JButton backend5;
    private javax.swing.JPanel backendMenu;
    private javax.swing.JTextField customerAddressInput;
    private javax.swing.JTextField customerBirthInput;
    private javax.swing.JTextField customerCorporateNameInput;
    private javax.swing.JButton customerEditButton;
    private javax.swing.JTextField customerEmailInput;
    private javax.swing.JTextField customerFnameInput;
    private javax.swing.JTextField customerLnameInput;
    private javax.swing.JTextArea customerNotesInput;
    private javax.swing.JTextField customerPhoneInput;
    private javax.swing.JTextField customerPostalCodeInput;
    private javax.swing.JButton customerRegisterButton;
    private javax.swing.JButton customerSearchButton;
    private javax.swing.JPanel customersPanel;
    private javax.swing.JPanel existPanel;
    private javax.swing.JTextField employee_ID_input;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton loginButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel Employee_ID_input_label;
    private javax.swing.JLabel Password_input_label;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loginErrorMessage_label;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton menuExistingButton;
    private javax.swing.JButton menuFindButton;
    private javax.swing.JButton menuRegButton;
    private javax.swing.JButton menuSingleOrderButton;
    private javax.swing.JButton menuSubscriptionButton;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel singleOrderDate;
    private javax.swing.JList singleOrderDateList;
    private javax.swing.JList singleOrderMonthList;
    private javax.swing.JPanel singleOrderPanel;
    private final javax.swing.JList singleOrderYearList = new javax.swing.JList();
    // End of variables declaration//GEN-END:variables
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
}